name: Docker Image 

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to scaleway
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/short-url-registry
          username: ${{secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}
      - run: |
          cd ShortenUrl 
          docker build . --tag short-url-api:$(date +%s)
